service: simple-project-alert-notification

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

functions: 
  get-generated-dog-name:
    handler: src/handlers/get-generated-dog-name/endpoint.handler
    events: 
      - http: 
          path: generate/{breed}/name
          method: get
          cors: true

  slack-notifications: 
    handler: src/handlers/slack-notification/slack-notification.handler
    environment: 
      SLACK_WEBHOOK_URL: ${ssm:/error-slack-webhook-url~true}
    events: 
      - sns: 
          arn: 
            Ref: DogSub
          topicName: ${self:service}-${self:provider.stage}-DogSub        

resources: # CloudFormation template syntax
  Resources:
    DogSub: #SNS
      Type: AWS::SNS::Topic
      Properties: 
        TopicName: DogBreed

    DoggoLogs: #Cloudwatch
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: DoggoAlert
        AlarmDescription: Get generated dog name lambda alarm
        Namespace: AWS/ApiGateway
        MetricName: 5XXError
        Dimensions:
          - Name: ApiName
            Value: ${self:provider.stage}-${self:service}
        Statistic: Sum
        ComparisonOperator: GreaterThanThreshold
        Threshold: 0
        Period: 60
        EvaluationPeriods: 1
        AlarmActions:
          - Ref: DogSub   